### ISSUE TITLE
Mailer\Manager construct request

### ISSUE THREAD

**Issue by etshy** [phalcon-ext/mailer#10]
Hi I would to know if It's will be a possibility to pass a Phalcon Config object in the construct.

+ the construct param is mandatory (the readme says it's optionnal and use the default viewsDir) 
It should take the getViewsDir() by default, and the params is not mandatory.

thanks for the module though, really helpful

**Comment by KorsaR-ZN** [comment]
@etshy 
If `viewsDir` parameter is not specified in the configuration, 
it is taken from `view` service of your application by default.

Please, show the sample code to understand what the problem
