### ISSUE TITLE
Doesn't support Phalcon 4.0+

### ISSUE THREAD

**Issue by themrdanielvp** [phalcon-ext/mailer#13]
Hi,
I am using this library with Phalcon 4.0 and above, but unfortunately the following error is thrown:

Class 'Phalcon\Mvc\User\Component' not found

This is easily fixable by changing the use of Phalcon\Mvc\User\Component to Phalcon\Di\Injectable

**Comment by KorsaR-ZN** [comment]
@themrdanielvp Thanks, fixed compatibility with Phalcon 4+

**Comment by kowach** [comment]
Hi,
there is another compatibility problem with return type.

Phalcon 4.1.0
PHP Version 7.4.16

Fatal error: Declaration of Phalcon\Ext\Mailer\Manager::getDI() must be compatible with Phalcon\Di\Injectable::getDI(): Phalcon\Di\DiInterface in ../vendor/phalcon-ext/mailer/src/Manager.php on line [424](https://github.com/phalcon-ext/mailer/blob/master/src/Manager.php#L424) 

It should be  `public function getDI(): DiInterface`

**Comment by KorsaR-ZN** [comment]
@kowach, Hi, I'll fix it this week

**Comment by KorsaR-ZN** [comment]
fixed on v3.0.1
