### ISSUE TITLE
HTML mail with plain text alternative

### ISSUE THREAD

**Issue by berliner** [phalcon-ext/mailer#3]
Hi,

maybe obvious, but I couldn't find information on this neither in the docs nor in the code:
Is it possible to send HTML formatted mails with a plain text alternative?
If so, could you tell me how?

Thanks in advance.

**Comment by KorsaR-ZN** [comment]
@berliner Hi,
I added new method in last commit, please update from `master` branch

*example*
```php
$mailer = new \Phalcon\Ext\Mailer\Manager($config);
$message = $mailer->createMessage()
        ->to('example_to@gmail.com', 'OPTIONAL NAME')
        ->subject('Hello world!')
        ->content('Hello world!');

   /**
    * Add optionally an alternative body
    *
    * @param string $content
    * @param string $contentType optional
    * @param string $charset     optional
    *
    * @return $this
    */
   $message->contentAlternative('Your text', $message::CONTENT_TYPE_PLAIN);
```

P.S
You can also use the method `$message->getSwiftMessage()` which returns instance `Swift_Message` see docs [SwiftMailer](https://github.com/swiftmailer/swiftmailer/blob/5.x/doc/messages.rst)

**Comment by berliner** [comment]
@KorsaR-ZN Thanks a lot. I wasn't sure that I can modify the result of ```$message->getSwiftMessage()```. It's working, very nice!

**Comment by KorsaR-ZN** [comment]
Thanks. The issue resolved? :)

**Comment by berliner** [comment]
Yes!

**Comment by fracz** [comment]
Can you release 2.0.3 version with this fix, please?

**Comment by KorsaR-ZN** [comment]
@fracz Added release 2.0.3
