### ISSUE TITLE
$params variable on createMessageFromView method is not begin send to view

### ISSUE THREAD

**Issue by itpedia-la** [phalcon-ext/mailer#4]
$params = array(
   'subject'  => 'Password Recovery',
   'fullname'	=> 'Fullname'
);

$this->mailer->createMessageFromView('password_recovery', $params)->to($user[0]['email'], $userInfo->firstname.' '.$userInfo->lastname)->subject('Password Recovery')->send();

so I have temporay fix this issue by add "$view->setVar('params',$params);" before the line number 320 in file name Manager.php

**Comment by KorsaR-ZN** [comment]
@itpedia-la You have to use so if you need subarray
```php
$params = array(
   'params' => array(
      'subject' => 'Password Recovery',
      'fullname' => 'Fullname'
   )
);

...
...createMessageFromView('password_recovery', $params);
...

```
