### ISSUE TITLE
Unable to auth using Google Apps 

### ISSUE THREAD

**Issue by RayHughes** [phalcon-ext/mailer#6]
When attempting to auth using a Google Apps gmail account (custom domain), the connection is refused as it not "secure". Attempted both tls and ssl. No issues with standard gmail accounts. Research points to it requiring oauth.

There is a work around available, you can elect to make your account less secure in the settings, but other features may be disabled. Sometimes a reduction in security for a feature is not an option.

**Comment by KorsaR-ZN** [comment]
Could you please show the configuration for mailer component?

**Comment by RayHughes** [comment]
Here is my implementation. Apologize for the delay.

`$config = [
			    'driver'     => 'smtp',
			    'host'       => 'smtp.gmail.com',
			    'port'       => 587,
			    'encryption' => 'tls',
			    'username'   => 'email@email.com',
			    'password'   => 'pass',
			    'from'       => [
	            	   'email' => email@email.com',
					'name'  => 'email name'
			        ]
			];
`

**Comment by KorsaR-ZN** [comment]
@RayHughes Yes, please create an account in your apps for me to test, and send account details to my email

**Comment by RayHughes** [comment]
Account details have been generated and sent to your email @KorsaR-ZN

**Comment by KorsaR-ZN** [comment]
@RayHughes I apologize for the delay, i had to leave...
Account that you created me does not work anymore?

**Comment by RayHughes** [comment]
I will deactivate it in a bit

**Comment by KorsaR-ZN** [comment]
@RayHughes You could enable it on again?

**Comment by KorsaR-ZN** [comment]
@RayHughes Try to use instead of a password, use token ([see](https://github.com/phalcon-ext/mailer#configure))

**Comment by RayHughes** [comment]
Do you still need the account?

**Comment by KorsaR-ZN** [comment]
Yes, if the issues is not solved yet ..

**Comment by RayHughes** [comment]
I have not tried. I will work on this weekend and recreate the user if
needed.

**Comment by KorsaR-ZN** [comment]
@RayHughes Ok, i then waiting feedback...
