### ISSUE TITLE
Problem with createMessageFromView()

### ISSUE THREAD

**Issue by w3soIutionsRO** [phalcon-ext/mailer#7]
Hello, if I try to send an email with template, I receive the email with Subject, but without content(template is not loading).
If I try without template( createMessage() ), is working properly.
Path to template is good...is very wierd.

**Comment by KorsaR-ZN** [comment]
You used of latest version?, Phalcon version?
Please show an example of how you use...

**Comment by w3soIutionsRO** [comment]
I'm using 2.0.7 version.

This is an example:
$template = 'email_templates/recover';
$params = array(
    'publicUrl' => 'VAR VALUE 1',
    'confirmUrl' => 'VAR VALUE 2',
    'varN' => 'VAR VALUE N',
);
$message = $this->mail->createMessageFromView($template, $params)
        ->to('example_to@gmail.com', 'OPTIONAL NAME')
        ->subject('Hello world!');

$message->send();

I receive email, but without content...and path is good because if I'm trying to change path from $template variable, I'm receiving an error.

**Comment by KorsaR-ZN** [comment]
You using component version 2.0.2 or higher?.
Please see #2 maybe related...

I can check it only tomorrow :(

**Comment by w3soIutionsRO** [comment]
I'm using latest version.
I tried also with phalcon incubator and still not working.

BTW, I use yonaCMS ( https://github.com/oleksandr-torosh/yona-cms/tree/master/  ).

**Comment by KorsaR-ZN** [comment]
@w3soIutionsRO 
I could not reproduce the problem.
Could you give an example of how you use it.

P.S. Please try on the latest version from branch `master` .

**Comment by w3soIutionsRO** [comment]
Hi, thanks for your help.
I fixed, I changed extension of template from .volt to .phtml and now is working properly.

**Comment by KorsaR-ZN** [comment]
@w3soIutionsRO This should work for .volt, maybe you have an error in the configuration
