### ISSUE TITLE
Swiftmailer v6

### ISSUE THREAD

**Issue by jimigrunge** [phalcon-ext/mailer#9]
The change in master to 'Allow composers use Swiftmailer v6' has not been tagged to a version. This is requiring the use of dev-master in order to install the package. 

This is causing an issue with my company's rules about usage of stable versions of third party packages as they are requiring SwiftMailer 6 for security reasons.

**Comment by KorsaR-ZN** [comment]
@jimigrunge Added release `v2.1.0`

**Comment by jimigrunge** [comment]
Thank you, composer updates worked with no problems.
